# This is a basic workflow to help you get started with Actions

name: dotnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run dotnet
        run: dotnet run -p generator/src/generator.csproj -- . "http://localhost:8000/" _site
        
      - name : copy asset
        run : ./copy-assets.bash _site
      - name : config
        run : | 
              git config --global user.email "gaga2353@gmail.com"
              git config --global user.name "bmlsj"
        
      - name: git push
        run: |
          git pull
          git add -f '_site'
          git commit -am "auto push"
          git push
          
      - name : check
        run : echo "finish"
