# This is a basic workflow to help you get started with Actions

name: run number

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - uses: actions/checkout@v3
  
      - name: env build_version
        env:
          BUILD_VER : ${{github.run_number}}
        run: echo "build version is $BUILD_VER"
